packages:
  - packages/*

catalog:
  '@antfu/eslint-config': ^7.3.0
  '@tanstack/vue-table': 8.21.3
  '@types/node': ^25.2.2
  '@vee-validate/zod': 4.15.1
  '@vueuse/core': 14.1.0
  embla-carousel-vue: 8.6.0
  lucide-vue-next: ^0.563.0
  markdownlint-cli: ^0.47.0
  nitro: 3.0.1-alpha.2
  reka-ui: 2.7.0
  rolldown: 1.0.0-rc.3
  tailwindcss: ^4.1.18
  typescript: ^5.9.3
  vaul-vue: 0.4.1
  vee-validate: 4.15.1
  vue: ^3.5.27
  vue-input-otp: 0.3.2
  vue-sonner: 2.0.9
  wrangler: ^4.63.0

catalogMode: prefer

cleanupUnusedCatalogs: true

onlyBuiltDependencies:
  - simple-git-hooks
