catalogMode: prefer
cleanupUnusedCatalogs: true
shellEmulator: true
trustPolicy: no-downgrade

trustPolicyExclude:
  - chokidar@4.0.3
  - langium@3.3.1

packages:
  - packages/*

overrides:
  semver: 7.7.3

catalog:
  '@antfu/eslint-config': ^7.3.0
  '@vueuse/core': ^14.1.0
  lucide-vue-next: ^0.555.0
  markdownlint-cli: ^0.47.0
  tailwindcss: ^4.1.17
  typescript: ^5.9.3
  vue: ^3.5.25
  vue-sonner: ^2.0.9
  zod: ^4.1.13

allowedDeprecatedVersions:
  '@types/parse-path': 7.1.0

onlyBuiltDependencies:
  - simple-git-hooks

peerDependencyRules:
  allowedVersions:
    zod: '4'
